# Generated by Django 5.2.4 on 2026-06-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_action_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('meeting_scheduled', 'Meeting Scheduled'), ('item_created', 'Item Created'), ('deadline_changed', 'Deadline Changed')], max_length=40),
        ),
    ]
