# Generated by Django 5.2.4 on 2026-06-08 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('icon', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('document', 'Document'), ('chart', 'Chart'), ('folder', 'Folder'), ('star', 'Star'), ('settings', 'Settings'), ('users', 'Users'), ('calendar', 'Calendar'), ('tag', 'Tag')], default='list', max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('access', models.CharField(choices=[('all', 'All Users'), ('admin', 'Admin Only'), ('poc', 'POC Only')], default='all', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('field_key', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('textarea', 'Long Text'), ('file', 'File Upload')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=120)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='menus.custommenu')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('menu', 'field_key')},
            },
        ),
    ]
