# Generated by Django 5.2.4 on 2026-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktask',
            name='hours_taken',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='worktask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
