# Generated by Django 5.2.4 on 2026-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='menu_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
