# Generated by Django 5.2.4 on 2026-06-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='E.164 without +, e.g. 919876543210', max_length=20),
        ),
    ]
