# Generated by Django 5.2.4 on 2026-06-03 09:35

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DOLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to=apps.documents.models.do_letter_upload_path)),
                ('description', models.TextField(blank=True)),
                ('visible_to_all', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('units', models.ManyToManyField(blank=True, related_name='do_letters', to='units.convergenceunit')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_doletter',
                'ordering': ['-date'],
            },
        ),
    ]
