# Generated by Django 5.2.4 on 2026-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doletter',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
