# Generated by Django 5.2.4 on 2026-06-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_doletter_tracking_number'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOLetterCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('is_compliant', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_compliance', to='units.convergenceunit')),
            ],
            options={
                'db_table': 'documents_dolettercompliance',
                'ordering': ['-year', '-month', 'unit__order'],
                'unique_together': {('unit', 'year', 'month')},
            },
        ),
    ]
