import { jsPDF } from 'jspdf';
import {
  Document, Packer, Paragraph, TextRun,
  AlignmentType, BorderStyle, TableRow, TableCell, Table,
  WidthType, ShadingType,
} from 'docx';

/* ── helpers ─────────────────────────────────── */
function fmtTime(t) {
  if (!t) return '';
  const [h, m] = t.split(':').map(Number);
  return ` ${h % 12 || 12}:${String(m).padStart(2,'0')} ${h < 12 ? 'AM' : 'PM'}`;
}

function slug(meeting) {
  const A = meeting.pair.unit_a.abbr, B = meeting.pair.unit_b.abbr;
  return `MoM_${A}_${B}_${meeting.date}`;
}

/* ══════════════════════════════════════════════
   PDF  (jsPDF — no canvas required)
══════════════════════════════════════════════ */
export function downloadPDF(meeting) {
  const doc  = new jsPDF({ unit: 'mm', format: 'a4' });
  const A    = meeting.pair.unit_a, B = meeting.pair.unit_b;
  const mins = meeting.minutes;

  const PW   = 210, PH = 297;
  const ML   = 18, MR = 18, MT = 18;
  const TW   = PW - ML - MR;
  let   y    = MT;

  const LINE  = 0.25;
  const accent = [63, 70, 225];   // #3f46e1 ≈ indigo

  // ── Header band ──────────────────────────────
  doc.setFillColor(...accent);
  doc.rect(0, 0, PW, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('MINUTES OF MEETING', ML, 13);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${A.name}  ×  ${B.name}`, ML, 21);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text('MS CMS — Model Schools CMS', PW - MR, 21, { align: 'right' });

  y = 36;

  // ── Meta row ─────────────────────────────────
  doc.setFillColor(246, 248, 255);
  doc.rect(ML, y, TW, 16, 'F');
  doc.setDrawColor(220, 225, 245);
  doc.setLineWidth(LINE);
  doc.rect(ML, y, TW, 16);

  doc.setTextColor(70, 80, 110);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const meta = [
    ['Date',     meeting.date + fmtTime(meeting.time)],
    ['Type',     meeting.mtype || 'In-person'],
    ['Attended', mins?.attendees || '—'],
  ];
  meta.forEach(([k, v], i) => {
    const x = ML + 8 + i * (TW / 3);
    doc.setFont('helvetica', 'bold');
    doc.text(k.toUpperCase(), x, y + 6);
    doc.setFont('helvetica', 'normal');
    doc.text(v, x, y + 12);
  });
  y += 22;

  // ── Section helper ───────────────────────────
  const section = (title, body, isTable = false) => {
    if (y > PH - 30) { doc.addPage(); y = MT; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...accent);
    doc.text(title.toUpperCase(), ML, y);
    doc.setDrawColor(...accent);
    doc.setLineWidth(0.4);
    doc.line(ML, y + 1.5, ML + TW, y + 1.5);
    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);

    if (!isTable) {
      const lines = doc.splitTextToSize(body, TW);
      lines.forEach(l => {
        if (y > PH - 20) { doc.addPage(); y = MT; }
        doc.text(l, ML, y);
        y += 5.5;
      });
    }
    y += 4;
  };

  // ── Agenda ───────────────────────────────────
  if (meeting.agenda) section('Agenda', meeting.agenda);

  // ── Summary ──────────────────────────────────
  if (mins?.summary) section('Summary / Discussion', mins.summary);

  // ── Action Points ────────────────────────────
  if (mins?.action_points?.length) {
    section('Action Points', '', true);
    mins.action_points.forEach((ap, idx) => {
      if (y > PH - 20) { doc.addPage(); y = MT; }
      const rowBg = idx % 2 === 0 ? [250, 251, 255] : [255, 255, 255];
      doc.setFillColor(...rowBg);
      doc.rect(ML, y - 4, TW, 8, 'F');

      // Status dot
      doc.setFillColor(ap.done ? 16 : 148, ap.done ? 185 : 163, ap.done ? 129 : 184);
      doc.circle(ML + 4, y, 2, 'F');

      doc.setFont('courier', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(...accent);
      doc.text(ap.aid, ML + 9, y + 0.5);

      doc.setFont('helvetica', ap.done ? 'normal' : 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(ap.done ? 148 : 30, ap.done ? 163 : 41, ap.done ? 184 : 59);
      const txt = doc.splitTextToSize(ap.text, TW - 28);
      doc.text(txt, ML + 24, y + 0.5);
      if (ap.done) {
        doc.setDrawColor(148, 163, 184);
        doc.setLineWidth(0.3);
        doc.line(ML + 24, y, ML + 24 + doc.getTextWidth(txt[0]), y);
      }
      y += Math.max(txt.length * 5, 8) + 2;
    });
  }

  // ── Footer ───────────────────────────────────
  doc.setFillColor(...accent);
  doc.rect(0, PH - 12, PW, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`Generated by MS CMS — Model Schools CMS  |  ${new Date().toLocaleDateString()}`, ML, PH - 4.5);

  doc.save(`${slug(meeting)}.pdf`);
}

/* ══════════════════════════════════════════════
   WORD (.docx)
══════════════════════════════════════════════ */
export async function downloadWord(meeting) {
  const A    = meeting.pair.unit_a, B = meeting.pair.unit_b;
  const mins = meeting.minutes;

  const accentHex = '3F46E1';
  const children  = [];

  // Title
  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'MINUTES OF MEETING', bold: true, size: 36, color: accentHex, font: 'Calibri' })],
      alignment: AlignmentType.LEFT,
      spacing: { after: 80 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `${A.name}  ×  ${B.name}`, bold: true, size: 28, font: 'Calibri' })],
      spacing: { after: 40 },
    }),
  );

  // Meta table
  const metaCell = (label, value) => new TableCell({
    children: [
      new Paragraph({ children: [new TextRun({ text: label.toUpperCase(), size: 16, color: '64748B', font: 'Calibri' })] }),
      new Paragraph({ children: [new TextRun({ text: value, bold: true, size: 20, font: 'Calibri' })] }),
    ],
    shading: { type: ShadingType.SOLID, color: 'F1F5FF', fill: 'F1F5FF' },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
  });

  children.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [new TableRow({ children: [
        metaCell('Date', meeting.date + fmtTime(meeting.time)),
        metaCell('Type', meeting.mtype || 'In-person'),
        metaCell('Attended', mins?.attendees || '—'),
      ]})],
    }),
    new Paragraph({ spacing: { after: 160 } }),
  );

  // Section helper
  const addSection = (title, content) => {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: title, bold: true, size: 22, color: accentHex, font: 'Calibri' })],
        border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: accentHex } },
        spacing: { before: 200, after: 80 },
      }),
      new Paragraph({
        children: [new TextRun({ text: content, size: 22, font: 'Calibri' })],
        spacing: { after: 160 },
      }),
    );
  };

  if (meeting.agenda) addSection('Agenda', meeting.agenda);
  if (mins?.summary)  addSection('Summary / Discussion', mins.summary);

  // Action Points
  if (mins?.action_points?.length) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: 'Action Points', bold: true, size: 22, color: accentHex, font: 'Calibri' })],
        border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: accentHex } },
        spacing: { before: 200, after: 80 },
      }),
    );
    mins.action_points.forEach(ap => {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: `${ap.done ? '☑' : '☐'}  `, size: 22, font: 'Calibri' }),
          new TextRun({ text: `${ap.aid}  `, bold: true, size: 20, color: accentHex, font: 'Courier New' }),
          new TextRun({ text: ap.text, size: 21, font: 'Calibri', strike: ap.done, color: ap.done ? '94A3B8' : '1E293B' }),
        ],
        spacing: { after: 60 },
      }));
    });
  }

  // Footer note
  children.push(
    new Paragraph({ spacing: { before: 400 } }),
    new Paragraph({
      children: [new TextRun({ text: `MS CMS — Model Schools CMS  |  ${new Date().toLocaleDateString()}`, size: 16, color: '94A3B8', font: 'Calibri' })],
      alignment: AlignmentType.RIGHT,
    }),
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url;
  a.download = `${slug(meeting)}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}
