# Generated by Django 5.2 on 2026-06-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvergenceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('abbr', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1A1A1F', max_length=20)),
                ('member_name', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'units_convergenceunit',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UnitPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_a', to='units.convergenceunit')),
                ('unit_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_b', to='units.convergenceunit')),
            ],
            options={
                'db_table': 'units_unitpair',
                'ordering': ['unit_a__order', 'unit_b__order'],
                'unique_together': {('unit_a', 'unit_b')},
            },
        ),
    ]
