# Generated by Django 5.2 on 2026-06-02 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('support', 'Support'), ('request', 'Request'), ('alert', 'Alert'), ('emergency', 'Emergency'), ('need', 'Need'), ('fund', 'Fund'), ('infra', 'Infra'), ('school', 'School'), ('student', 'Student')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('raiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_items', to='units.convergenceunit')),
                ('targets', models.ManyToManyField(related_name='received_items', to='units.convergenceunit')),
            ],
            options={
                'db_table': 'items_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='items.item')),
            ],
            options={
                'db_table': 'items_itemactionitem',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
