# Generated by Django 5.2.4 on 2026-06-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
