# Generated by Django 5.2 on 2026-06-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_assigned_to_sla_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='item',
            name='original_deadline',
        ),
    ]
