# Generated by Django 5.2 on 2026-06-02 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'meetings_actionpoint',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActionPointComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetings.actionpoint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings_actionpointcomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('conducted', 'Conducted'), ('postponed', 'Postponed'), ('missed', 'Missed')], default='scheduled', max_length=15)),
                ('mtype', models.CharField(choices=[('In-person', 'In-person'), ('Online', 'Online')], default='In-person', max_length=15)),
                ('agenda', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('notify_units', models.ManyToManyField(blank=True, related_name='notified_meetings', to='units.convergenceunit')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='units.unitpair')),
            ],
            options={
                'db_table': 'meetings_meeting',
                'ordering': ['-date', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('written', 'Written'), ('upload', 'Uploaded')], default='written', max_length=10)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='mom_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_minutes', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meetings_meetingminutes',
            },
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='minutes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='meetings.meetingminutes'),
        ),
        migrations.CreateModel(
            name='MeetingNotHeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('postponed', 'Postponed'), ('missed', 'Missed')], default='postponed', max_length=15)),
                ('reason', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_held_records', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='not_held', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meetings_meetingnotheld',
            },
        ),
    ]
